config/routes.rb
Rails.application.routes.draw do

  root 'fisheries#index'


  resources :matches
  resources :hatches
  resources :bugs
  resources :flies
  resources :fisheries
  devise_for :users
end

app/models/hatch.rb
# == Schema Information
#
# Table name: hatches
#
#  id           :integer          not null, primary key
#  end_day      :integer
#  end_month    :string
#  maximum_size :string
#  minimum_size :string
#  start_day    :integer
#  start_month  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  bug_id       :integer
#  fishery_id   :integer
#
# Indexes
#
#  index_hatches_on_bug_id      (bug_id)
#  index_hatches_on_fishery_id  (fishery_id)
#
# Foreign Keys
#
#  bug_id      (bug_id => bugs.id)
#  fishery_id  (fishery_id => fisheries.id)
#
class Hatch < ApplicationRecord
  belongs_to :bug
  belongs_to :fishery
end

app/controllers/hatches_controller.rb
class HatchesController < ApplicationController
  before_action :set_hatch, only: %i[ show edit update destroy ]

  # GET /hatches or /hatches.json
  def index
    @hatches = Hatch.all
  end

  # GET /hatches/1 or /hatches/1.json
  def show
  end

  # GET /hatches/new
  def new
    @hatch = Hatch.new
  end

  # GET /hatches/1/edit
  def edit
  end

  # POST /hatches or /hatches.json
  def create
    @hatch = Hatch.new(hatch_params)

    respond_to do |format|
      if @hatch.save
        format.html { redirect_to hatch_url(@hatch), notice: "Hatch was successfully created." }
        format.json { render :show, status: :created, location: @hatch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hatches/1 or /hatches/1.json
  def update
    respond_to do |format|
      if @hatch.update(hatch_params)
        format.html { redirect_to hatch_url(@hatch), notice: "Hatch was successfully updated." }
        format.json { render :show, status: :ok, location: @hatch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hatches/1 or /hatches/1.json
  def destroy
    @hatch.destroy

    respond_to do |format|
      format.html { redirect_to hatches_url, notice: "Hatch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hatch
      @hatch = Hatch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hatch_params
      params.require(:hatch).permit(:bug_id, :fishery_id, :minimum_size, :maximum_size, :start_month, :start_day, :end_month, :end_day)
    end
end

app/views/hatches/_form.html.erb
<%= form_with(model: hatch, local: true) do |form| %>
  <% if hatch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hatch.errors.count, "error") %> prohibited this hatch from being saved:</h2>

      <ul>
        <% hatch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bug_id %>
    <%= form.text_field :bug_id %>
  </div>

  <div class="field">
    <%= form.label :fishery_id %>
    <%= form.text_field :fishery_id %>
  </div>

  <div class="field">
    <%= form.label :minimum_size %>
    <%= form.text_field :minimum_size %>
  </div>

  <div class="field">
    <%= form.label :maximum_size %>
    <%= form.text_field :maximum_size %>
  </div>

  <div class="field">
    <%= form.label :start_month %>
    <%= form.text_field :start_month %>
  </div>

  <div class="field">
    <%= form.label :start_day %>
    <%= form.number_field :start_day %>
  </div>

  <div class="field">
    <%= form.label :end_month %>
    <%= form.text_field :end_month %>
  </div>

  <div class="field">
    <%= form.label :end_day %>
    <%= form.number_field :end_day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hatches/edit.html.erb
<h1>Editing Hatch</h1>

<%= render 'form', hatch: @hatch %>

<%= link_to 'Show', @hatch %> |
<%= link_to 'Back', hatches_path %>

app/views/hatches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hatches</h1>

<table>
  <thead>
    <tr>
      <th>Bug</th>
      <th>Fishery</th>
      <th>Minimum size</th>
      <th>Maximum size</th>
      <th>Start month</th>
      <th>Start day</th>
      <th>End month</th>
      <th>End day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hatches.each do |hatch| %>
      <tr>
        <td><%= hatch.bug_id %></td>
        <td><%= hatch.fishery_id %></td>
        <td><%= hatch.minimum_size %></td>
        <td><%= hatch.maximum_size %></td>
        <td><%= hatch.start_month %></td>
        <td><%= hatch.start_day %></td>
        <td><%= hatch.end_month %></td>
        <td><%= hatch.end_day %></td>
        <td><%= link_to 'Show', hatch %></td>
        <td><%= link_to 'Edit', edit_hatch_path(hatch) %></td>
        <td><%= link_to 'Destroy', hatch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hatch', new_hatch_path %>

app/views/hatches/new.html.erb
<h1>New Hatch</h1>

<%= render 'form', hatch: @hatch %>

<%= link_to 'Back', hatches_path %>

app/views/hatches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bug:</strong>
  <%= @hatch.bug_id %>
</p>

<p>
  <strong>Fishery:</strong>
  <%= @hatch.fishery_id %>
</p>

<p>
  <strong>Minimum size:</strong>
  <%= @hatch.minimum_size %>
</p>

<p>
  <strong>Maximum size:</strong>
  <%= @hatch.maximum_size %>
</p>

<p>
  <strong>Start month:</strong>
  <%= @hatch.start_month %>
</p>

<p>
  <strong>Start day:</strong>
  <%= @hatch.start_day %>
</p>

<p>
  <strong>End month:</strong>
  <%= @hatch.end_month %>
</p>

<p>
  <strong>End day:</strong>
  <%= @hatch.end_day %>
</p>

<%= link_to 'Edit', edit_hatch_path(@hatch) %> |
<%= link_to 'Back', hatches_path %>