config/routes.rb
Rails.application.routes.draw do

  root 'fisheries#index'


  resources :matches
  resources :hatches
  resources :bugs
  resources :flies
  resources :fisheries
  devise_for :users
end

app/models/fly.rb
# == Schema Information
#
# Table name: flies
#
#  id          :integer          not null, primary key
#  description :string
#  name        :string
#  photo       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Fly < ApplicationRecord
  has_many  :matches, dependent: :destroy
end

app/controllers/flies_controller.rb
class FliesController < ApplicationController
  before_action :set_fly, only: %i[ show edit update destroy ]

  # GET /flies or /flies.json
  def index
    @flies = Fly.all
  end

  # GET /flies/1 or /flies/1.json
  def show
  end

  # GET /flies/new
  def new
    @fly = Fly.new
  end

  # GET /flies/1/edit
  def edit
  end

  # POST /flies or /flies.json
  def create
    @fly = Fly.new(fly_params)

    respond_to do |format|
      if @fly.save
        format.html { redirect_to fly_url(@fly), notice: "Fly was successfully created." }
        format.json { render :show, status: :created, location: @fly }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flies/1 or /flies/1.json
  def update
    respond_to do |format|
      if @fly.update(fly_params)
        format.html { redirect_to fly_url(@fly), notice: "Fly was successfully updated." }
        format.json { render :show, status: :ok, location: @fly }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flies/1 or /flies/1.json
  def destroy
    @fly.destroy

    respond_to do |format|
      format.html { redirect_to flies_url, notice: "Fly was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fly
      @fly = Fly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fly_params
      params.require(:fly).permit(:name, :photo, :description)
    end
end

app/views/flies/_form.html.erb
<%= form_with(model: fly, local: true) do |form| %>
  <% if fly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fly.errors.count, "error") %> prohibited this fly from being saved:</h2>

      <ul>
        <% fly.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flies/edit.html.erb
<h1>Editing Fly</h1>

<%= render 'form', fly: @fly %>

<%= link_to 'Show', @fly %> |
<%= link_to 'Back', flies_path %>

app/views/flies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Photo</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flies.each do |fly| %>
      <tr>
        <td><%= fly.name %></td>
        <td><%= fly.photo %></td>
        <td><%= fly.description %></td>
        <td><%= link_to 'Show', fly %></td>
        <td><%= link_to 'Edit', edit_fly_path(fly) %></td>
        <td><%= link_to 'Destroy', fly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fly', new_fly_path %>

app/views/flies/new.html.erb
<h1>New Fly</h1>

<%= render 'form', fly: @fly %>

<%= link_to 'Back', flies_path %>

app/views/flies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fly.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @fly.photo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fly.description %>
</p>

<%= link_to 'Edit', edit_fly_path(@fly) %> |
<%= link_to 'Back', flies_path %>